openapi: 3.0.1
info:
  title: Pet Store API
  version: 1.0.0
paths:
  /pets:
    get:
      summary: Get a list of all pets
      operationId: listPets
      responses:
        '200':
          description: A list of pets
          content:
            application/json:
              example:
                - id: 1
                  name: Dog
                - id: 2
                  name: Cat
    post:
      summary: Add a new pet to the store
      operationId: addPet
      requestBody:
        description: The pet to add
        required: true
        content:
          application/json:
            example:
              id: 3
              name: Rabbit
              owner: John
      responses:
        '201':
          description: Pet added successfully
          content:
            application/json:
              example:
                id: 3
                name: Rabbit
        '400':
          description: Bad request
          content:
            application/json:
              example:
                message: Invalid request body
  /pets/{id}:
    get:
      summary: Find a pet by ID
      operationId: findPetById
      parameters:
        - name: id
          in: path
          description: The ID of the pet to retrieve
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: The pet
          content:
            application/json:
              example:
                - id: 1
                  name: Dog
        '404':
          description: Pet not found
          content:
            application/json:
              example:
                message: Pet not found
  /pets/{id}/owner:
    get:
      summary: Find the owner of a pet
      operationId: findOwner
      parameters:
        - name: id
          in: path
          description: The ID of the pet
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: The owner
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                  name:
                    type: string
        '404':
          description: Pet not found
          content:
            application/json:
              example:
                message: Pet not found              
components:
  schemas:
    Pet:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
